[workspace]
members = ["kobe", "kobe-btc", "kobe-eth", "kobe-xmr"]
default-members = ["kobe"]

resolver = "3"

[workspace.dependencies]
kobe = { path = "./kobe", default-features = false }
kobe-btc = { path = "./kobe-btc", default-features = false }
kobe-eth = { path = "./kobe-eth", default-features = false }
kobe-xmr = { path = "./kobe-xmr", default-features = false }

bech32 = { version = "0.11", default-features = false, features = ["alloc"] }
bip32 = { version = "0.5", default-features = false, features = ["secp256k1", "alloc"] }
bip39 = { version = "2.1", default-features = false, features = ["alloc"] }
bs58 = { version = "0.5", default-features = false, features = ["alloc", "check"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
hex-literal = "1.1.0"
hmac = { version = "0.12", default-features = false }
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "schnorr"] }
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
rand = { version = "0.9.2", default-features = false }
rand_core = { version = "0.9.5", default-features = false }
ripemd = { version = "0.1", default-features = false }
sha2 = { version = "0.10", default-features = false }
sha3 = { version = "0.10", default-features = false }
subtle = { version = "2.5", default-features = false }
zeroize = { version = "1.7", default-features = false, features = ["derive"] }

[profile.release]
lto = true           # Enable Link Time Optimization to remove unused code
codegen-units = 1    # Maximize optimization at the cost of slower compilation
panic = 'abort'      # Remove panic handling to reduce binary size
strip = true         # Fully strip debug symbols; debugging in production will be difficult
